### ISSUE TITLE
./boost/thread/pthread/thread_data.hpp:60:5: error: missing binary operator before token "(" 60 | #if PTHREAD_STACK_MIN > 0

### ISSUE THREAD

**Issue by mathnovel** [mathnovel/DayCollection#8]

**Comment by mathnovel** [comment]
https://github.com/prusa3d/PrusaSlicer/issues/8145

say that newer boost version would be ok,but i didn't try now

**Comment by mathnovel** [comment]
why error occur ,look at https://github.com/BitcoinUnlimited/BitcoinUnlimited/commit/878546a15ca258c17b6e5a947320e9bc0c4da468

build: Fix boost depends build with glibc >= 2.34
Summary
---

In glibc >= 2.34 `PTHREAD_STACK_MIN` has been made dynamic which causes
Boost 1.70 to fail to build.

This has been fixed in https://github.com/boostorg/thread/pull/297 for
Solaris which also uses a function call for `PTHREAD_STACK_MIN`.

See:

* https://github.com/fabaff/nixpkgs/commit/629e53164bf3f2389813e51e9a984a998559abba
* https://github.com/boostorg/thread/issues/364
* https://github.com/boostorg/thread/issues/283

Test plan
---

* Use a build OS that includes glibc >= 3.34 (eg Ubuntu 22.04)
* `cd depends`
* `make HOST=x86_64-pc-linux-gnu`

**Comment by mathnovel** [comment]
# my  raspberry pi glibc version

```bash
ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
````

 >= 2.34
